I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'images/side/phone_dim.png'>:
  File "game/script.rpy", line 11, in script
    l default "Let's see..."
IOError: Couldn't find file 'images/side/phone_dim.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\bootstrap.py", line 306, in bootstrap
    renpy.main.main()
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\main.py", line 513, in main
    run(restart)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\main.py", line 139, in run
    renpy.execution.run_context(True)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\execution.py", line 879, in run_context
    context.run()
  File "game/script.rpy", line 11, in script
    l default "Let's see..."
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\ast.py", line 652, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\exports.py", line 1199, in say
    who(what, *args, **kwargs)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\character.py", line 1016, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\character.py", line 817, in do_display
    **display_args)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\character.py", line 566, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\core.py", line 2649, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\core.py", line 3132, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\core.py", line 2055, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 485, in renpy.display.render.render_screen
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\screen.py", line 669, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "accelerator.pyx", line 108, in renpy.display.accelerator.transform_render
  File "render.pyx", line 233, in renpy.display.render.render
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\im.py", line 580, in render
    return cache.get(self, render=True)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\im.py", line 266, in get
    surf = image.load()
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\display\im.py", line 625, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File "D:\Renpy\renpy-7.0.0-sdk\renpy\loader.py", line 555, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'images/side/phone_dim.png'.

Windows-8-6.2.9200
Ren'Py 7.0.0.196
Escape Roomba 0.0
Tue Sep 18 21:52:46 2018
